// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using StockPlatform.API.Database;

#nullable disable

namespace StockPlatform.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260701055643_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("StockPlatform.API.Models.Company", b =>
                {
                    b.Property<int>("CompanyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("company_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CompanyId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Industry")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("industry");

                    b.Property<decimal?>("MarketCap")
                        .HasColumnType("numeric")
                        .HasColumnName("market_cap");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("Sector")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("sector");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("ticker");

                    b.HasKey("CompanyId");

                    b.HasIndex("Ticker")
                        .IsUnique();

                    b.HasIndex("Sector", "MarketCap");

                    b.ToTable("companies");
                });

            modelBuilder.Entity("StockPlatform.API.Models.Financial", b =>
                {
                    b.Property<int>("FinancialId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("financial_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("FinancialId"));

                    b.Property<int>("CompanyId")
                        .HasColumnType("integer")
                        .HasColumnName("company_id");

                    b.Property<decimal?>("DebtToEquity")
                        .HasColumnType("numeric")
                        .HasColumnName("debt_to_equity");

                    b.Property<decimal?>("Eps")
                        .HasColumnType("numeric")
                        .HasColumnName("eps");

                    b.Property<decimal?>("NetIncome")
                        .HasColumnType("numeric")
                        .HasColumnName("net_income");

                    b.Property<DateOnly>("ReportDate")
                        .HasColumnType("date")
                        .HasColumnName("report_date");

                    b.Property<decimal?>("Revenue")
                        .HasColumnType("numeric")
                        .HasColumnName("revenue");

                    b.Property<decimal?>("RevenueGrowth")
                        .HasColumnType("numeric")
                        .HasColumnName("revenue_growth");

                    b.Property<decimal?>("Roe")
                        .HasColumnType("numeric")
                        .HasColumnName("roe");

                    b.HasKey("FinancialId");

                    b.HasIndex("CompanyId", "ReportDate");

                    b.ToTable("financials");
                });

            modelBuilder.Entity("StockPlatform.API.Models.Financial", b =>
                {
                    b.HasOne("StockPlatform.API.Models.Company", "Company")
                        .WithMany("Financials")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("StockPlatform.API.Models.Company", b =>
                {
                    b.Navigation("Financials");
                });
#pragma warning restore 612, 618
        }
    }
}
