// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using StockPlatform.API.Database;

#nullable disable

namespace StockPlatform.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260710044740_InitialBaseline")]
    partial class InitialBaseline
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("StockPlatform.API.Models.Company", b =>
                {
                    b.Property<int>("CompanyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("company_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CompanyId"));

                    b.Property<string>("Country")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("country");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Exchange")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("exchange");

                    b.Property<string>("Industry")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("industry");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<decimal?>("MarketCap")
                        .HasColumnType("numeric")
                        .HasColumnName("market_cap");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<int?>("SectorId")
                        .HasColumnType("integer")
                        .HasColumnName("sector_id");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("ticker");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("CompanyId");

                    b.HasIndex("SectorId");

                    b.HasIndex("Ticker")
                        .IsUnique();

                    b.ToTable("companies");
                });

            modelBuilder.Entity("StockPlatform.API.Models.EtlLog", b =>
                {
                    b.Property<int>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("log_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("LogId"));

                    b.Property<string>("ErrorMsg")
                        .HasColumnType("text")
                        .HasColumnName("error_msg");

                    b.Property<int?>("RowsLoaded")
                        .HasColumnType("integer")
                        .HasColumnName("rows_loaded");

                    b.Property<DateTime>("RunDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("run_date");

                    b.Property<string>("Source")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("source");

                    b.Property<string>("Status")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.HasKey("LogId");

                    b.ToTable("etl_log");
                });

            modelBuilder.Entity("StockPlatform.API.Models.Financial", b =>
                {
                    b.Property<int>("FinancialId")
                        .HasColumnType("integer")
                        .HasColumnName("financial_id");

                    b.Property<int>("FiscalYear")
                        .HasColumnType("integer")
                        .HasColumnName("fiscal_year");

                    b.Property<decimal?>("Cash")
                        .HasColumnType("numeric")
                        .HasColumnName("cash");

                    b.Property<int>("CompanyId")
                        .HasColumnType("integer")
                        .HasColumnName("company_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal?>("CurrentRatio")
                        .HasColumnType("numeric")
                        .HasColumnName("current_ratio");

                    b.Property<decimal?>("DebtToEquity")
                        .HasColumnType("numeric")
                        .HasColumnName("debt_to_equity");

                    b.Property<decimal?>("Ebitda")
                        .HasColumnType("numeric")
                        .HasColumnName("ebitda");

                    b.Property<decimal?>("Eps")
                        .HasColumnType("numeric")
                        .HasColumnName("eps");

                    b.Property<short?>("FiscalQuarter")
                        .HasColumnType("smallint")
                        .HasColumnName("fiscal_quarter");

                    b.Property<decimal?>("GrossProfit")
                        .HasColumnType("numeric")
                        .HasColumnName("gross_profit");

                    b.Property<decimal?>("NetIncome")
                        .HasColumnType("numeric")
                        .HasColumnName("net_income");

                    b.Property<decimal?>("OperatingIncome")
                        .HasColumnType("numeric")
                        .HasColumnName("operating_income");

                    b.Property<string>("PeriodType")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("period_type");

                    b.Property<decimal?>("ProfitMargin")
                        .HasColumnType("numeric")
                        .HasColumnName("profit_margin");

                    b.Property<DateOnly>("ReportDate")
                        .HasColumnType("date")
                        .HasColumnName("report_date");

                    b.Property<decimal?>("Revenue")
                        .HasColumnType("numeric")
                        .HasColumnName("revenue");

                    b.Property<decimal?>("RevenueGrowth")
                        .HasColumnType("numeric")
                        .HasColumnName("revenue_growth");

                    b.Property<decimal?>("Roa")
                        .HasColumnType("numeric")
                        .HasColumnName("roa");

                    b.Property<decimal?>("Roe")
                        .HasColumnType("numeric")
                        .HasColumnName("roe");

                    b.Property<decimal?>("TotalAssets")
                        .HasColumnType("numeric")
                        .HasColumnName("total_assets");

                    b.Property<decimal?>("TotalDebt")
                        .HasColumnType("numeric")
                        .HasColumnName("total_debt");

                    b.Property<decimal?>("TotalEquity")
                        .HasColumnType("numeric")
                        .HasColumnName("total_equity");

                    b.Property<decimal?>("TotalLiabilities")
                        .HasColumnType("numeric")
                        .HasColumnName("total_liabilities");

                    b.HasKey("FinancialId", "FiscalYear");

                    b.HasIndex("CompanyId", "ReportDate");

                    b.ToTable("financials");
                });

            modelBuilder.Entity("StockPlatform.API.Models.MlPrediction", b =>
                {
                    b.Property<int>("PredictionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("prediction_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PredictionId"));

                    b.Property<string>("Classification")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("classification");

                    b.Property<int>("CompanyId")
                        .HasColumnType("integer")
                        .HasColumnName("company_id");

                    b.Property<decimal?>("Confidence")
                        .HasColumnType("numeric")
                        .HasColumnName("confidence");

                    b.Property<string>("ModelVersion")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("model_version");

                    b.Property<DateTime>("PredictedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("predicted_at");

                    b.Property<string>("TopFeatures")
                        .HasColumnType("jsonb")
                        .HasColumnName("top_features");

                    b.HasKey("PredictionId");

                    b.HasIndex("CompanyId");

                    b.ToTable("ml_predictions");
                });

            modelBuilder.Entity("StockPlatform.API.Models.Sector", b =>
                {
                    b.Property<int>("SectorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("sector_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SectorId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("SectorId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("sectors");
                });

            modelBuilder.Entity("StockPlatform.API.Models.StockPrice", b =>
                {
                    b.Property<long>("PriceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("price_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("PriceId"));

                    b.Property<decimal?>("AdjClose")
                        .HasColumnType("numeric")
                        .HasColumnName("adj_close");

                    b.Property<decimal?>("ClosePrice")
                        .HasColumnType("numeric")
                        .HasColumnName("close_price");

                    b.Property<int>("CompanyId")
                        .HasColumnType("integer")
                        .HasColumnName("company_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal?>("HighPrice")
                        .HasColumnType("numeric")
                        .HasColumnName("high_price");

                    b.Property<decimal?>("LowPrice")
                        .HasColumnType("numeric")
                        .HasColumnName("low_price");

                    b.Property<decimal?>("OpenPrice")
                        .HasColumnType("numeric")
                        .HasColumnName("open_price");

                    b.Property<DateOnly>("PriceDate")
                        .HasColumnType("date")
                        .HasColumnName("price_date");

                    b.Property<long?>("Volume")
                        .HasColumnType("bigint")
                        .HasColumnName("volume");

                    b.HasKey("PriceId");

                    b.HasIndex("CompanyId", "PriceDate")
                        .IsUnique();

                    b.ToTable("stock_prices");
                });

            modelBuilder.Entity("StockPlatform.API.Models.Company", b =>
                {
                    b.HasOne("StockPlatform.API.Models.Sector", "Sector")
                        .WithMany("Companies")
                        .HasForeignKey("SectorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Sector");
                });

            modelBuilder.Entity("StockPlatform.API.Models.Financial", b =>
                {
                    b.HasOne("StockPlatform.API.Models.Company", "Company")
                        .WithMany("Financials")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("StockPlatform.API.Models.MlPrediction", b =>
                {
                    b.HasOne("StockPlatform.API.Models.Company", "Company")
                        .WithMany("MlPredictions")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("StockPlatform.API.Models.StockPrice", b =>
                {
                    b.HasOne("StockPlatform.API.Models.Company", "Company")
                        .WithMany("StockPrices")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("StockPlatform.API.Models.Company", b =>
                {
                    b.Navigation("Financials");

                    b.Navigation("MlPredictions");

                    b.Navigation("StockPrices");
                });

            modelBuilder.Entity("StockPlatform.API.Models.Sector", b =>
                {
                    b.Navigation("Companies");
                });
#pragma warning restore 612, 618
        }
    }
}
